### ISSUE TITLE
can't create new space

### ISSUE THREAD

**Issue by riccardoklinger** [heremaps/xyz-qgis-plugin#16]
I tried to create a new space with an "all-in" token. Unfortunately it shows me some WRITE issues:
Request:
https://xyz.api.here.com/hub/spaces

Response:
{"type":"ErrorResponse","streamId":"8717d1df-7e1c-11e9-beed-dbc5dfb205cb","error":"Exception","errorMessage":"Insufficient rights. Token access: {\"manageSpaces\":[{\"owner\":\"HERE-0217530d-346e-41cc-abad-252821e8b2de\",\"space\":\"Gxt7o9l9\"}],\"createFeatures\":[{\"owner\":\"HERE-0217530d-346e-41cc-abad-252821e8b2de\",\"space\":\"Gxt7o9l9\"}],\"updateFeatures\":[{\"owner\":\"HERE-0217530d-346e-41cc-abad-252821e8b2de\",\"space\":\"Gxt7o9l9\"}],\"deleteFeatures\":[{\"owner\":\"HERE-0217530d-346e-41cc-abad-252821e8b2de\",\"space\":\"Gxt7o9l9\"}],\"readFeatures\":[{\"owner\":\"HERE-0217530d-346e-41cc-abad-252821e8b2de\",\"space\":\"Gxt7o9l9\"}]}\nRequest access: {\"manageSpaces\":[{\"owner\":\"HERE-0217530d-346e-41cc-abad-252821e8b2de\",\"space\":\"99cmJ0rh\",\"packages\":[]}]}"}

the layer is a point layer with 200 points QGIS 3.4.4, Python 3.5.2.

**Comment by minff** [comment]
Did you generate the token on https://xyz.api.here.com/token-ui ?
What is the description of this token found in Manage Tokens tab ?

**Comment by riccardoklinger** [comment]
xyz-hub=createFeatures,manageSpaces,readFeatures,updateFeatures,deleteFeatures

**Comment by riccardoklinger** [comment]
the TOKEN_UI_MASTER_TOKEN token works for creating new spaces.
