### ISSUE TITLE
Doesnt connect

### ISSUE THREAD

**Issue by musictomy** [heremaps/xyz-qgis-plugin#56]
No longer connects, wrong url settings etc, they have moved

**Comment by jolauer** [comment]
I assume you are trying to connect to the XYZ HUB spaces? 

We did integrate access to the HERE platform via the Interactive Map Layers (IML).
You just need to use your HERE Platform account to connect or create a new one
https://developer.here.com/products/platform
Hope this solves your issue?

**Comment by musictomy** [comment]
I already tried with my account details, i log in but the plugin does nothing. is this where I can actuall search key values and alter what i see on map data like OSM, as i sometimes use the map  web > quickmapservices > Here Wego > terraine

As I look the apearance of this map, but was trying to find a way of loosing the labels, i assumed this plugin does this.

Sorry if i am completly at the wrong side of what I am trying to do

**Comment by jolauer** [comment]
With the HERE QGIS Plugin, you can connect to the HERE Platform and interact with the Interactive Map Layers (e.g. collaborative work on geospatial data). Further, you can request the HERE Tiles service and visualize the rendered HERE Map (different Styles) in QGIS. You can request different styles - one of them might fit your use-case?

**Comment by musictomy** [comment]
Still wont connect me > as per screen grab, is it a paid service?
![here](https://github.com/heremaps/xyz-qgis-plugin/assets/8762957/fc5825ce-3ca2-42b5-967c-6dd82e0a32da)

**Comment by musictomy** [comment]
Its ok got connected, had to add billing to get organisation Id etc, have api keys etc, so just exploring now, thx for the help
