### ISSUE TITLE
Is the custom repo necessary?

### ISSUE THREAD

**Issue by pcav** [heremaps/xyz-qgis-plugin#7]

**Comment by jolauer** [comment]
Hi Paolo,
thanks for your feedback!
We used this way as an interim solution until the plugin has been approved for the official repository.
Thanks for your patience.

Regards,
Johannes

**Comment by pcav** [comment]
So could you please remove it, so I can proceed with publication?
A bit of a hen-egg problem, in fact ;)

**Comment by pcav** [comment]
Anyway, publishing it in the meantime.
Thanks.
